### ISSUE TITLE
some question hope  to solve

### ISSUE THREAD

**Issue by searchlink** [igeti/keras_elmo_bert#1]
@igeti 
 Thanks for your code! I wonder about the ```self.output_representation```, I think ```self.output_representation == 'mean_pooling'```,the output shape should be [batch_size, 768].
 In addition, ```result = self.bert(inputs=bert_inputs, signature="tokens", as_dict=True), what is meaning of result["pooled_output"] and result["sequence_output"]  ``` . 
About ```def compute_mask()```, why appoint ```self.output_representation == 'sequence_output'```, how to compute result["sequence_output"]?

**Comment by igeti** [comment]
@searchlink  Thank you for asking! Unfortunately I made mistakes when describing BERT Layer, you are right with the output shape. As for the values of outputs, it is better to read here in the official information (Original Bert https://github.com/google-research/bert and tf-hub BERT https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1). Accordingly, since the mask is thus the input of this module, we take output mask as a slice of input list.
